apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "moebius.labels" . | nindent 4 }}
data:
  NATS_URL: {{ if .Values.nats.external }}{{ .Values.nats.externalUrl | quote }}{{ else }}"nats://{{ .Release.Name }}-nats:4222"{{ end }}
  CA_CERT_PATH: {{ .Values.secrets.caCertPath | quote }}
  CA_KEY_PATH: {{ .Values.secrets.caKeyPath | quote }}
