apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "moebius.labels" . | nindent 4 }}
data:
  CA_CERT_PATH: {{ .Values.secrets.caCertPath | quote }}
  CA_KEY_PATH: {{ .Values.secrets.caKeyPath | quote }}
