{{- if .Values.secrets.databaseUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    {{- include "moebius.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
{{- end }}
