{{- if .Values.api.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "moebius.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
