run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - misspell
    - gofmt

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
  misspell:
    locale: US
