# Production / SaaS overrides

api:
  replicaCount: 5
  autoscaling:
    enabled: true
    minReplicas: 5
    maxReplicas: 40
    targetCPUUtilizationPercentage: 60
  podDisruptionBudget:
    minAvailable: 3
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1Gi

scheduler:
  replicaCount: 2
