{{- if .Values.worker.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app.kubernetes.io/component: worker
    {{- include "moebius.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
